# Generated by Django 3.0.3 on 2020-04-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20200405_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='esta_seleccionado',
            field=models.BooleanField(default=False),
        ),
    ]
