# Generated by Django 3.0.3 on 2020-04-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_videos_esta_seleccionado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
    ]
