# Generated by Django 3.0.3 on 2020-04-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20200405_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalYT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('link', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='descri',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='fechaPub',
            field=models.DateTimeField(null=True, verbose_name='publicado'),
        ),
        migrations.AddField(
            model_name='video',
            name='img',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='ytid',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='titulo',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
