# Generated by Django 3.0.3 on 2020-04-06 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20200406_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='canal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.CanalYT'),
        ),
    ]
